### ISSUE TITLE
ALTER時のforceオプション

### ISSUE THREAD

**Issue by ilhagiharar** [howyi/conv#22]
https://github.com/howyi/conv/blob/8394871c875b4415b44daa601fdff50377d12ba1/src/Conv/Generator/TableAlterMigrationGenerator.php#L184

CIでTableAlterMigrationGeneratorを利用しています。

このユースケースだと、ALTERのオプションでCIが止まる場合があるため、forceオプションによって挙動を一律にするオプションがあると便利です。

CIでは、以下のようにスキーマ定義から直接DBへの適用を行うコマンドを作って実行しています。

https://github.com/howyi/conv-laravel/issues/2

**Comment by shoji-mochizuki** [comment]
開発時の使用を想定しているのでdrop側の挙動で動いて欲しいです。
この辺が想定する箇所かなーと思いましたので提案させていただきました。

```
# オプション指定時には質問をスキップしてdroppedで動くようにしたい
            $answer = $operator->choiceQuestion(
                sprintf('Column %s.%s is missing. Choose an action.', $beforeTable->tableName, $missingField),
                ['dropped', sprintf('renamed (%s)', implode(', ', $addedFieldList))]
            );
            if ('dropped' === $answer) {
                $droppedFieldList[] = $missingField;
                continue;
            }
```

**Comment by ilhagiharar** [comment]
他にいい方法があればご提案くださいー

**Comment by howyi** [comment]
なるほど。

**Comment by ilhagiharar** [comment]
Resolved #23 

ご対応ありがとうございましたー！ 🙏
