### ISSUE TITLE
不正なDDLを渡した際に例外とする案

### ISSUE THREAD

**Issue by hgsk** [howyi/conv#41]
PDOが実行できない不正なDDLを渡した際に問題となる箇所を把握したいと考えています。

下記の箇所で例外を送出、ないし、警告を出力してはどうでしょうか。

なんらかの例外が出ていれば使う側でcatchできるため、例外の方が望ましいと考えていますが、影響範囲は確認できていません。

下記のコードです。

https://github.com/howyi/conv/blob/master/src/DatabaseStructureFactory.php#L134

```
正常時

>>> $this->pdo->exec($this->query);
=> 0

異常時
>>> $this->pdo->exec($this->query);
=> false
```

対応策として、PDOのオプションを渡すか、戻り値を見て例外を送出する手段が考えられます。

http://php.net/manual/en/pdo.query.php#65543

後ほどPRを出しますのでご検討いただけますでしょうか。

**Comment by howyi** [comment]
使用していただきありがとうございます ❗️ 🙏 
確かに不親切ですね... 対応していただけると大変ありがたいです、よろしくおねがいします 🙇
