### ISSUE TITLE
mariadb support

### ISSUE THREAD

**Issue by nutsh3ll** [howyi/conv#45]
Hi.

We want to use this package(via howyi/conv-laravel) with mariadb, but [DriverAllocator](https://github.com/howyi/conv/blob/master/src/Driver/DriverAllocator.php) throws ` RuntimeException  : Unsupported driver. conv supported MySQL 5.6.*|5.7.*|8.0.*
`.

Currently, we use docker image of `mariadb:10.3.15` and the driver version is like following:
```
$ ./artisan tinker
Psy Shell v0.9.12 (PHP 7.4.0 — cli) by Justin Hileman
>>> $conn = app('db')->connection()
=> App\Infrastructure\Database\Connection\MySqlConnection {#356}
>>> $conn->getPdo()->getAttribute(\PDO::ATTR_DRIVER_NAME)
=> "mysql"
>>> $conn->getPdo()->getAttribute(\PDO::ATTR_SERVER_VERSION)
=> "5.5.5-10.3.15-MariaDB-1:10.3.15+maria~bionic-log"
```

Do you have any good ideas about this?

**Comment by howyi** [comment]
https://github.com/howyi/conv/pull/46
MariaDB(10.0~) support on v2.1.0 🎉 🌮 🎉 🌮 🎉 🌮 🎉 🌮 🎉 🌮 🎉 🌮 
https://github.com/howyi/conv/releases/tag/v2.1.0

**Comment by nutsh3ll** [comment]
Works fine! Really appreciate your help!
