### ISSUE TITLE
composer installがコケるらしい

### ISSUE THREAD

**Issue by howyi** [howyi/conv#9]
.lock消したら直るらしい

**Comment by 844196** [comment]
rubyとかnode, goの経験しかなくてあれなんですが…

ライブラリを使用する側のアプリはロックを含めますが、ライブラリにはlockファイルは入れない気がしてます。

https://kohkimakimoto.github.io/getcomposer.org_doc_jp/doc/01-basic-usage.html

**Comment by 844196** [comment]
composerはlockファイルがない場合、現在のPHPバージョンでインストール可能な最新のパッケージを落とします。マシンにインストールされているPHPのバージョンが、convが要求するPHP7.0.16以上かつ7.0系最新のPHP7.0.21の場合、 `doctrine/instantiator` はPHP5.3以上を要求するv1.0.5がインストールされます。

が、lockファイルにはPHP7.1を要求する `doctrine/instantiator` v1.1.0 を入れろと書いてあるのでコケています。

**Comment by howyi** [comment]
く、詳しそう… ありがとうございます。
開発時のライブラリ管理としてはアプリもライブラリも変わらないのかな〜と思いつつなんとなくノリで入れてみましたけど、そこまでバージョンを絞ったところで感もあり、ていうか壊れてるなら無い方がいいなとなり、とりあえず消しました 🐎 
https://github.com/howyi/conv/commit/c468d494b49a3d1196073a76ab4a7acdd1a0868d

**Comment by howyi** [comment]
おおお消してる間に詳細な内容まで！ありがとうございますありがとうございます… 🙇

**Comment by 844196** [comment]
@howyi 

<p align="center"><img src="https://user-images.githubusercontent.com/4990822/28975953-fb9c5156-7976-11e7-8159-25d3e068067b.png"><br>fetchしたら動きました</p>

あや、大したことはしてないです  
これから触ってみます。ご対応ありがとうございましたー

**Comment by howyi** [comment]
ﾜｰありがとうございますっす 🐤
